/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travelagency.databse3;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author DELL
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();

        jPanel1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFname = new javax.swing.JTextField();
        TFbirthday = new javax.swing.JTextField();
        TFmobileno = new javax.swing.JTextField();
        TFemail = new javax.swing.JTextField();
        TFusername = new javax.swing.JTextField();
        TFpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ButEkle = new javax.swing.JButton();
        ButGuncelle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButYeniKisi = new javax.swing.JButton();
        ButKisiSil = new javax.swing.JButton();
        ButKisiGuncelle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Birthday");

        jLabel3.setText("Mobile Number");

        jLabel4.setText("E-mail");

        jLabel5.setText("Username");

        jLabel7.setText("Passwprd");

        ButEkle.setText("Add");
        ButEkle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButEkleMouseClicked(evt);
            }
        });

        ButGuncelle.setText("Update");
        ButGuncelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButGuncelleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(51, 51, 51)
                                .addComponent(TFbirthday))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFpassword)
                                    .addComponent(TFusername)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(TFname, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFmobileno)
                                    .addComponent(TFemail))))
                        .addGap(139, 139, 139))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(ButEkle)
                .addGap(29, 29, 29)
                .addComponent(ButGuncelle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TFbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TFusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButGuncelle)
                    .addComponent(ButEkle))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Tel No", "E-mail", "Birth of Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        ButYeniKisi.setText("New Customer");
        ButYeniKisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButYeniKisiMouseClicked(evt);
            }
        });

        ButKisiSil.setText("Delete Customer");
        ButKisiSil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButKisiSilMouseClicked(evt);
            }
        });

        ButKisiGuncelle.setText("Update Customer");
        ButKisiGuncelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButKisiGuncelleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(ButYeniKisi)
                .addGap(61, 61, 61)
                .addComponent(ButKisiSil)
                .addGap(54, 54, 54)
                .addComponent(ButKisiGuncelle)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButKisiGuncelle)
                    .addComponent(ButKisiSil)
                    .addComponent(ButYeniKisi))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:




    }//GEN-LAST:event_jTable1ComponentShown

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:


        
    }//GEN-LAST:event_jTable1MouseClicked

    public JTextField getTFbirthday() {
        return TFbirthday;
    }

    public void setTFbirthday(JTextField TFbirthday) {
        this.TFbirthday = TFbirthday;
    }

    public JTextField getTFemail() {
        return TFemail;
    }

    public void setTFemail(JTextField TFemail) {
        this.TFemail = TFemail;
    }

    public JTextField getTFmobileno() {
        return TFmobileno;
    }

    public void setTFmobileno(JTextField TFmobileno) {
        this.TFmobileno = TFmobileno;
    }

    public JTextField getTFname() {
        return TFname;
    }

    public void setTFname(JTextField TFname) {
        this.TFname = TFname;
    }

    private void ButYeniKisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButYeniKisiMouseClicked
        // TODO add your handling code here:

        jPanel1.setVisible(true);
        ButYeniKisi.setVisible(true);
        ButGuncelle.setVisible(false);
        TFpassword.setVisible(true);
        TFusername.setVisible(true);
        jLabel5.setVisible(true);
        jLabel7.setVisible(true);
        ButEkle.setVisible(true);

        TFbirthday.setText("");
        TFemail.setText("");
        TFmobileno.setText("");
        TFname.setText("");



    }//GEN-LAST:event_ButYeniKisiMouseClicked

    private void ButKisiSilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButKisiSilMouseClicked
        // TODO add your handling code here:




        int SelectedRow = jTable1.getSelectedRow();

        int cusid;
        cusid = Integer.parseInt((String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 0))));

        PreparedStatement ps1;




            try {





                int bookid = 0;
                ResultSet rs1;
                String query1 = "SELECT  `Book ID` FROM `manage` WHERE `Cus ID`=? ";
                ps1 = NewClass.getConnection().prepareStatement(query1);
                ps1.setInt(1, cusid);
                rs1 = ps1.executeQuery();
                while (rs1.next()) {
                    bookid = rs1.getInt(1);

                    String query4 = "DELETE FROM `manage` WHERE `Book ID`=?";

                    ps1 = NewClass.getConnection().prepareStatement(query4);
                    ps1.setInt(1, (bookid));

                    if (ps1.executeUpdate() > 0) {

                      //  JOptionPane.showMessageDialog(null, "User deleted");
                    }

                    String query2 = "DELETE FROM `booking` WHERE `Booking ID` =?";

                    ps1 = NewClass.getConnection().prepareStatement(query2);
                    ps1.setInt(1, (bookid));

                    if (ps1.executeUpdate() > 0) {

                    //    JOptionPane.showMessageDialog(null, "New user Add");
                    }

                }


                String query5 = "DELETE FROM `customer` WHERE `Customer ID`=?";

                ps1 = NewClass.getConnection().prepareStatement(query5);
                ps1.setInt(1, (cusid));

                if (ps1.executeUpdate() > 0) {

                    JOptionPane.showMessageDialog(null, "User deleted");
                }

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();


                model.removeRow(SelectedRow);

                jTable1.setModel(model);



    } catch (Exception a) {
                JOptionPane.showMessageDialog(null, a.getMessage());

            }



}//GEN-LAST:event_ButKisiSilMouseClicked

    private void ButGuncelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButGuncelleMouseClicked
        // TODO add your handling code here:

        int SelectedRow = jTable1.getSelectedRow();


        String col1 =TFname.getText();
        String col2=TFmobileno.getText();
        String col3=TFemail.getText();
        String col4= TFbirthday.getText();


        PreparedStatement ps1;
        String query1 = "UPDATE `customer` SET `Customer Name`=?,`Mobile Number`=?,`Email`=?,`Birthday`=? WHERE `Customer ID`=?";
        try {
            ps1=NewClass.getConnection().prepareStatement(query1);

            ps1.setString(1,col1);
            ps1.setString(2,col2);
            ps1.setString(3,col3);
            ps1.setString(4,col4);
            ps1.setInt(5,cusid);

            if(ps1.executeUpdate()>0){
                JOptionPane.showMessageDialog(null,"User updated");}


            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            model.setValueAt(col1, SelectedRow, 1);
            model.setValueAt(col2, SelectedRow, 2);
            model.setValueAt(col3, SelectedRow, 3);
            model.setValueAt(col4, SelectedRow, 4);


            jTable1.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_ButGuncelleMouseClicked

    private void ButEkleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButEkleMouseClicked
        // TODO add your handling code here:
        
             
        String  isim = TFname.getText();
        String  birth  = TFbirthday.getText();
        String  telefon = TFmobileno.getText();
        String   email = TFemail.getText();
        String  username = TFusername.getText();
        String password=String.valueOf(TFpassword.getPassword());



        PreparedStatement ps1;
        String query1 = "INSERT INTO `login`(`Username`, `Password`) VALUES (?,?)";
        try {

            ps1=NewClass.getConnection().prepareStatement(query1);

            ps1.setString(1,username);
            ps1.setString(2,password);

            if(ps1.executeUpdate()>0){
                JOptionPane.showMessageDialog(null,"New user added");}
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        int temp = 0;
        try {

            Statement stmt = NewClass.getConnection().createStatement();
        ResultSet rs;
        rs = stmt.executeQuery("SELECT * FROM `Login` WHERE username=username");
        while(rs.next()) {
            temp= rs.getInt(1);
        }


        PreparedStatement ps2;
        String query2="INSERT INTO `customer`( `Customer Name`, `Mobile Number`, `Email`, `Birthday`, `Login ID`) VALUES (?,?,?,?,?)";


            ps2=NewClass.getConnection().prepareStatement(query2);
            ps2.setString(1,isim);
            ps2.setString(2,telefon);
            ps2.setString(3,email);
            ps2.setString(4,birth);
            ps2.setInt(5,temp);


            if(ps2.executeUpdate()>0){
            //   JOptionPane.showMessageDialog(null,"New user Add");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
        
    }//GEN-LAST:event_ButEkleMouseClicked

    private int cusid =0;

    private void ButKisiGuncelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButKisiGuncelleMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        TFpassword.setVisible(false);
        TFusername.setVisible(false);
        jLabel5.setVisible(false);
        jLabel7.setVisible(false);
        ButEkle.setVisible(false);
        ButGuncelle.setVisible(true);

        int SelectedRow = jTable1.getSelectedRow();

        cusid = Integer.parseInt((String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 0)) ));

        String name = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 1));
        TFname.setText(name);

        String telno = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 2));
        TFmobileno.setText(telno);

        String email = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 3));
        TFemail.setText(email);

        String birth = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 4));
        TFbirthday.setText(birth);



    }//GEN-LAST:event_ButKisiGuncelleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });



    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButEkle;
    private javax.swing.JButton ButGuncelle;
    private javax.swing.JButton ButKisiGuncelle;
    private javax.swing.JButton ButKisiSil;
    private javax.swing.JButton ButYeniKisi;
    private javax.swing.JTextField TFbirthday;
    private javax.swing.JTextField TFemail;
    private javax.swing.JTextField TFmobileno;
    private javax.swing.JTextField TFname;
    private javax.swing.JPasswordField TFpassword;
    private javax.swing.JTextField TFusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
