/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travelagency.databse3;

import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author DELL
 */
public class AdminProfile extends javax.swing.JFrame {

    /**
     * Creates new form AdminProfile
     */
    public AdminProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Customers");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton3.setText("Trips");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Update Proife");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton2.setText("Log Out");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static BilgiUpdate b = new BilgiUpdate();

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        b.getButCusProfil().setVisible(false);

        b.getTableRez().setVisible(false);

        b.getjScrollPane2().setVisible(false);
        b.setVisible(true);


        int log = Login.Loginid;

        PreparedStatement ps1;
        ResultSet rs;
        String query=" SELECT  `Admin Name`, `Admin Telephone`, `Admin Email`, `Admin Birthday` FROM `admin` WHERE `Login ID`=?" ;



        try {
            ps1=NewClass.getConnection().prepareStatement(query);
            ps1.setInt(1,log);

            rs=ps1.executeQuery();

            while (rs.next())
            {

                b.getTFname().setText(rs.getString(1));
                b.getTFmobileno().setText(rs.getString(2));
                b.getTFemail().setText(rs.getString(3));
                b.getTFbirthday().setText(rs.getString(4));

            }






        } catch (Exception a) {
            System.out.println(a.getMessage());
        }




    }//GEN-LAST:event_jButton4MouseClicked

   private static Admin admin= new Admin();

    public static int cusid =0;

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:


        admin.setVisible(true);

        String col1 ="";
        String col2="";
        String col3="";
        String col4= "5";
        int col0=0;

        DefaultTableModel model = (DefaultTableModel) admin.getjTable1().getModel();
        PreparedStatement ps1;
        ResultSet rs;
        String query=" SELECT  `Customer Name`, `Mobile Number`, `Email`, `Birthday`, `Customer ID` FROM `customer` WHERE 1 " ;
        try {
            ps1=NewClass.getConnection().prepareStatement(query);
            rs=ps1.executeQuery();

            while (rs.next())
            {
                col1=rs.getString(1);
                col2=rs.getString(2);
                col3=rs.getString(3);
                col4=rs.getString(4);
                col0=rs.getInt(5);


                model.addRow(new Object[]{col0, col1, col2, col3, col4});

                admin.getjTable1().setModel(model);

            }

        } catch (Exception a) {
            System.out.println(a.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private static AdminTrip at = new AdminTrip();

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        at.setVisible(true);

        String col1 ="";
        String col2="";
        String col3="";
        String col4= "5";
        String col5= "5";
        String col6= "5";
        String col0= "";
        String col7= "";
        String col8= "";

        DefaultTableModel model = (DefaultTableModel) at.getjTable1().getModel();
        PreparedStatement ps1;
        ResultSet rs;
        String query=" SELECT  `Departure City`, `Arrival City`, `Departure Time`, `Arrival Time`, `Price`, `Trip Date`, `License Plate`, `Number of Seats`,`Trip ID` FROM `trip` WHERE 1 " ;
        try {
            ps1=NewClass.getConnection().prepareStatement(query);
            rs=ps1.executeQuery();

            while (rs.next())
            {

                col0=rs.getString(9);
                col1=rs.getString(1)  ;
                col2=rs.getString(2) ;
                col3=rs.getString(3);
                col4=rs.getString(4);
                col5=rs.getString(5);
                col6=rs.getString(6);

                col7=rs.getString(7);
                col8=rs.getString(8);



                model.addRow(new Object[]{col0, col1, col2, col3, col4, col5, col6, col7, col8});

                at.getjTable1().setModel(model);

            }

        } catch (Exception a) {
            System.out.println(a.getMessage());
        }
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
        
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProfile().setVisible(true);
            }
        });

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                b.setVisible(false);
            }
        });

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 admin.setVisible(false);
            }
        });

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                at.setVisible(false);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
