/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travelagency.databse3;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author DELL
 */
public class AdminTrip extends javax.swing.JFrame {

    /**
     * Creates new form AdminTrip
     */
    public AdminTrip() {
        initComponents();
        jPanel1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFDate = new javax.swing.JTextField();
        TFDepTime = new javax.swing.JTextField();
        TFPrice = new javax.swing.JTextField();
        ButEkle = new javax.swing.JButton();
        ButGuncelle = new javax.swing.JButton();
        TFArrTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TFPlaka = new javax.swing.JTextField();
        TFSeat = new javax.swing.JTextField();
        TFDepCity = new javax.swing.JTextField();
        TFArrCity = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButTripGuncelle = new javax.swing.JButton();
        ButTripSil = new javax.swing.JButton();
        ButYeniTrip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("City");

        jLabel2.setText("Date");

        jLabel3.setText("Time");

        jLabel4.setText("Price");

        ButEkle.setText("Add");
        ButEkle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButEkleMouseClicked(evt);
            }
        });

        ButGuncelle.setText("Update");
        ButGuncelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButGuncelleMouseClicked(evt);
            }
        });

        jLabel5.setText("Trip");

        jLabel6.setText("Bus");

        jLabel7.setText("Licence Plate");

        jLabel8.setText("Number of Seats");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(ButEkle)
                        .addGap(34, 34, 34)
                        .addComponent(ButGuncelle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3))
                                                    .addGap(45, 45, 45))
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(40, 40, 40)
                                                        .addComponent(TFPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                                        .addComponent(TFDepTime, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(TFArrTime, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(40, 40, 40)
                                                    .addComponent(TFPlaka, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(TFSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addComponent(TFDate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(TFDepCity, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TFArrCity, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFDepCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFArrCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TFDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFDepTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFArrTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TFPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TFPlaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TFSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButGuncelle)
                    .addComponent(ButEkle))
                .addGap(44, 44, 44))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trip No", "Departure City", "Arrival City", "Departure Time", "Arrival Time", "Price", "Date", "Licence Plate", "Number of Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
        }

        ButTripGuncelle.setText("Update Trip");
        ButTripGuncelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButTripGuncelleMouseClicked(evt);
            }
        });

        ButTripSil.setText("Delete Trip");
        ButTripSil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButTripSilMouseClicked(evt);
            }
        });

        ButYeniTrip.setText("New Trip");
        ButYeniTrip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButYeniTripMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ButYeniTrip)
                        .addGap(49, 49, 49)
                        .addComponent(ButTripSil)
                        .addGap(18, 18, 18)
                        .addComponent(ButTripGuncelle)
                        .addGap(288, 288, 288))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButTripGuncelle)
                    .addComponent(ButTripSil)
                    .addComponent(ButYeniTrip)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void ButYeniTripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButYeniTripMouseClicked
        // TODO add your handling code here:
        TFPlaka.setText("");
        TFDate.setText("");
        TFArrTime.setText("");
        TFDepTime.setText("");
        TFArrCity.setText("");
        TFDepCity.setText("");
        TFSeat.setText("");
        TFPrice.setText("");

        jPanel1.setVisible(true);
        ButEkle.setVisible(true);
        ButGuncelle.setVisible(false);

    }//GEN-LAST:event_ButYeniTripMouseClicked

    private void ButEkleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButEkleMouseClicked
        // TODO add your handling code here:

        

        int log = Login.Loginid;
        int agencyid=0;
        PreparedStatement ps1;
        ResultSet rs1;

        try {
        String query2 = "SELECT  `Agency ID` FROM `admin` WHERE `Login ID`=? ";

        ps1 = NewClass.getConnection().prepareStatement(query2);
        ps1.setInt(1, log);
        rs1=ps1.executeQuery();
        while (rs1.next()) {


            agencyid = rs1.getInt(1);
        }

            String query3 = "INSERT INTO `trip`( `Departure City`, `Arrival City`, `Departure Time`, `Arrival Time`, `Price`, `Trip Date`, `License Plate`, `Number of Seats`, `Agency ID`) VALUES (?,?,?,?,?,?,?,?,?)";


            ps1 = NewClass.getConnection().prepareStatement(query3);
            ps1.setString(1,TFDepCity.getText());
            ps1.setString(2,TFArrCity.getText());
            ps1.setString(3,TFDepTime.getText());
            ps1.setString(4,TFArrTime.getText());
            ps1.setInt(5, Integer.parseInt(TFPrice.getText()));
            ps1.setString(6,TFDate.getText());
            ps1.setString(7,TFPlaka.getText());
            ps1.setInt(8, Integer.parseInt(TFSeat.getText()));
            ps1.setInt(9, agencyid);

            if (ps1.executeUpdate() > 0) {

                JOptionPane.showMessageDialog(null, "New  trip added");
            }

        }

             catch (Exception a) {
            System.out.println(a.getMessage());
        }

        
    }//GEN-LAST:event_ButEkleMouseClicked

    private int tripid =0;

    private void ButTripGuncelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButTripGuncelleMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        ButEkle.setVisible(false);
        ButGuncelle.setVisible(true);


        int SelectedRow = jTable1.getSelectedRow();

        tripid = Integer.parseInt((String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 0)) ));

        String depcity = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 1));
        TFDepCity.setText(depcity);

        String arrcity = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 2));
        TFArrCity.setText(arrcity);

        String deptime = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 3));
        TFDepTime.setText(deptime);

        String arrtime = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 4));
        TFArrTime.setText(arrtime);

        String price = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 5));
        TFPrice.setText(price);

        String date = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 6));
        TFDate.setText(date);

        String plaka = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 7));
        TFPlaka.setText(plaka);

        String seat = String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 8));
        TFSeat.setText(seat);


     
    }//GEN-LAST:event_ButTripGuncelleMouseClicked

    private void ButGuncelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButGuncelleMouseClicked
        // TODO add your handling code here:

        PreparedStatement ps1;
        String query1 = "UPDATE `trip` SET `Departure City`=? ,`Arrival City`=? ,`Departure Time`=? ,`Arrival Time`=?,`Price`=?,`Trip Date`=? ,`License Plate`=?,`Number of Seats`=? WHERE `Trip ID`=?";
        try {
            ps1=NewClass.getConnection().prepareStatement(query1);

            ps1.setString(1,TFDepCity.getText());
            ps1.setString(2,TFArrCity.getText());
            ps1.setString(3,TFDepTime.getText());
            ps1.setString(4,TFArrTime.getText());
            ps1.setInt(5, Integer.parseInt(TFPrice.getText()));
            ps1.setString(6,TFDate.getText());
            ps1.setString(7,TFPlaka.getText());
            ps1.setInt(8, Integer.parseInt(TFSeat.getText()));
            ps1.setInt(9, tripid);

            if(ps1.executeUpdate()>0){
                JOptionPane.showMessageDialog(null,"Trip updated");}


            int SelectedRow = jTable1.getSelectedRow();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            model.setValueAt(TFDepCity.getText(), SelectedRow, 1);
            model.setValueAt(TFArrCity.getText(), SelectedRow, 2);
            model.setValueAt(TFDepTime.getText(), SelectedRow, 3);
            model.setValueAt(TFArrTime.getText(), SelectedRow, 4);
            model.setValueAt(TFPrice.getText(), SelectedRow, 5);
            model.setValueAt(TFDate.getText(), SelectedRow, 6);
            model.setValueAt(TFPlaka.getText(), SelectedRow, 7);
            model.setValueAt(TFSeat.getText(), SelectedRow, 8);

            jTable1.setModel(model);


        } catch (Exception e) {
            System.out.println(e.getMessage());
        }


        
    }//GEN-LAST:event_ButGuncelleMouseClicked

    private void ButTripSilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButTripSilMouseClicked
        // TODO add your handling code here:

        int SelectedRow = jTable1.getSelectedRow();

        tripid = Integer.parseInt((String.valueOf(jTable1.getModel().getValueAt(SelectedRow, 0)) ));


        PreparedStatement ps1;
        PreparedStatement ps2;
        try {
            String query1 = "DELETE FROM `manage` WHERE `Trip ID`=?";

            ps1 = NewClass.getConnection().prepareStatement(query1);
            ps1.setInt(1, (tripid));

            String query2 = "DELETE FROM `trip` WHERE `Trip ID`=?";

            ps2 = NewClass.getConnection().prepareStatement(query2);
            ps2.setInt(1, (tripid));


            if (ps1.executeUpdate() > 0) {

            //    JOptionPane.showMessageDialog(null, "");
            }
            if (ps2.executeUpdate() > 0) {

                JOptionPane.showMessageDialog(null, "Trip deleted");
            }
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            model.removeRow(SelectedRow);


            jTable1.setModel(model);

        }

        catch (Exception a) {
            System.out.println(a.getMessage());
        }


    }//GEN-LAST:event_ButTripSilMouseClicked

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTrip().setVisible(true);
            }
        });
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButEkle;
    private javax.swing.JButton ButGuncelle;
    private javax.swing.JButton ButTripGuncelle;
    private javax.swing.JButton ButTripSil;
    private javax.swing.JButton ButYeniTrip;
    private javax.swing.JTextField TFArrCity;
    private javax.swing.JTextField TFArrTime;
    private javax.swing.JTextField TFDate;
    private javax.swing.JTextField TFDepCity;
    private javax.swing.JTextField TFDepTime;
    private javax.swing.JTextField TFPlaka;
    private javax.swing.JTextField TFPrice;
    private javax.swing.JTextField TFSeat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
