/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travelagency.databse3;

import java.awt.EventQueue;
import javax.swing.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author DELL
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFusername = new javax.swing.JTextField();
        TFpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButLogin = new javax.swing.JButton();
        ButSignup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        ButLogin.setText("Log in");
        ButLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButLoginMouseClicked(evt);
            }
        });

        ButSignup.setText("Sign Up");
        ButSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButSignupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(TFusername))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButSignup)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButLogin)
                    .addComponent(ButSignup))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static int Loginid;


    public static String username;


    public static int cusid = 11;
    private void ButLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButLoginMouseClicked
        // TODO add your handling code here:
        
         username =TFusername.getText();
        String password=String.valueOf(TFpassword.getPassword());
        
        
        PreparedStatement ps1;
        ResultSet rs;
        String query="SELECT * FROM Login WHERE `Username`=? AND `Password`=?";
        try {
             ps1=NewClass.getConnection().prepareStatement(query);    
             ps1.setString(1,username);
             ps1.setString(2,password);
             rs=ps1.executeQuery();
             if(rs.next())
             {
                 JOptionPane.showMessageDialog(null,"You are in ");
                 Loginid = rs.getInt(1);
                 String l = rs.getString(2);
                 System.out.println(Loginid + l);


                 Login k =new Login();
                 System.out.println(Login.username);

                 if (l.equals("Admin")) {
                     java.awt.EventQueue.invokeLater(new Runnable() {
                         public void run() {
                             new AdminProfile().setVisible(true);
                       //      login.setDefaultCloseOperation(login.DISPOSE_ON_CLOSE)  ;

                         }

                     }
                     );
                     login.setVisible(false);

                 }

               else  if (l.equals("Customer")) {
                     java.awt.EventQueue.invokeLater(new Runnable() {
                         public void run() {
                             new Profile().setVisible(true);
                         }
                     });

                     login.setVisible(false);
                 }




             }
             else
               JOptionPane.showMessageDialog(null,"Please check your information and try again");

            int log = Login.Loginid;
            ResultSet rs2 = null;


            PreparedStatement ps2;

            String query2 = "SELECT `Customer ID` FROM Customer WHERE `Login ID` =? ";

            ps2 = NewClass.getConnection().prepareStatement(query2);
            ps2.setInt(1, log);
            rs2=ps2.executeQuery();
            while (rs2.next()) {



                cusid = rs2.getInt(1);
            }





        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_ButLoginMouseClicked

    private void ButSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButSignupMouseClicked
        // TODO add your handling code here:
            EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);

            }
        });
            login.setVisible(false);
    }//GEN-LAST:event_ButSignupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               login.setVisible(true);
            }
        });
    }

    public static Login login = new Login();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButLogin;
    private javax.swing.JButton ButSignup;
    private javax.swing.JPasswordField TFpassword;
    private javax.swing.JTextField TFusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
