/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travelagency.databse3;

import sun.rmi.runtime.Log;

import java.awt.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author DELL
 */
public class NewJFrame extends javax.swing.JFrame {

    
    

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFname = new javax.swing.JTextField();
        TFbirthday = new javax.swing.JTextField();
        TFmobileno = new javax.swing.JTextField();
        TFemail = new javax.swing.JTextField();
        TFusername = new javax.swing.JTextField();
        TFpassword = new javax.swing.JPasswordField();
        ButSignup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButSignup.setText("Sign Up");
        ButSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButSignupMouseClicked(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Birthday");

        jLabel3.setText("Mobile Number");

        jLabel4.setText("E-mail");

        jLabel5.setText("Username");

        jLabel7.setText("Passwprd");

        jLabel6.setText("(Ex 1990-05-28)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(ButSignup)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFmobileno)
                            .addComponent(TFbirthday)
                            .addComponent(TFpassword)
                            .addComponent(TFemail)
                            .addComponent(TFusername)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TFname, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(ButSignup)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButSignupMouseClicked

            
      String  isim = TFname.getText();
      String  birth  = TFbirthday.getText();
      String  telefon = TFmobileno.getText();
      String   email = TFemail.getText();
      String  username = TFusername.getText();
      String password=String.valueOf(TFpassword.getPassword());



        PreparedStatement ps1;
        String query1 = "INSERT INTO `login`(`Username`, `Password`) VALUES (?,?)";
        try {

            ps1=NewClass.getConnection().prepareStatement(query1);

            ps1.setString(1,username);
            ps1.setString(2,password);

            if(ps1.executeUpdate()>0){
           //     JOptionPane.showMessageDialog(null,"New user Add");
                   }


        int temp = 0;
        Statement stmt = NewClass.getConnection().createStatement();
        ResultSet rs;
        rs = stmt.executeQuery("SELECT * FROM `Login` WHERE username=username");
        while(rs.next()) {
            temp= rs.getInt(1);
        }


        PreparedStatement ps2;
        String query2="INSERT INTO `customer`( `Customer Name`, `Mobile Number`, `Email`, `Birthday`, `Login ID`) VALUES (?,?,?,?,?)";


            ps2=NewClass.getConnection().prepareStatement(query2);
            ps2.setString(1,isim);
            ps2.setString(2,telefon);
            ps2.setString(3,email);
            ps2.setString(4,birth);
            ps2.setInt(5,temp);


            if(ps2.executeUpdate()>0){
                JOptionPane.showMessageDialog(null,"New user Add");
                nf.setVisible(false);
                Login.login.setVisible(true);


            }
            else {
                JOptionPane.showMessageDialog(null,"Please check your information and try  again");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Please check your information and try  again");

        }



    }//GEN-LAST:event_ButSignupMouseClicked



    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>



        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                nf.setVisible(true);
            }
        });
    }

    public static NewJFrame nf = new NewJFrame();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButSignup;
    private javax.swing.JTextField TFbirthday;
    private javax.swing.JTextField TFemail;
    private javax.swing.JTextField TFmobileno;
    private javax.swing.JTextField TFname;
    private javax.swing.JPasswordField TFpassword;
    private javax.swing.JTextField TFusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
