/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travelagency.databse3;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import javax.swing.text.NumberFormatter;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.NumberFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author DELL
 */
public class Purchase extends javax.swing.JFrame {

    public JButton getButPurcGuncelle() {
        return ButPurcGuncelle;
    }

    public void setButPurcGuncelle(JButton ButPurcGuncelle) {
        this.ButPurcGuncelle = ButPurcGuncelle;
    }

    public JButton getButPurcTrip() {
        return ButPurcTrip;
    }

    public void setButPurcTrip(JButton ButPurcTrip) {
        this.ButPurcTrip = ButPurcTrip;
    }

    /**
     * Creates new form Purchase
     */

    final int[] l1 = {0};
    final int[] l2 = {0};
    final int[] l3 = {0};
    final int[] l4 = {0};
    final int[] l5 = {0};

    public static Purchase purcc;

    static {
        purcc = new Purchase();
    }
    public Purchase() {
        initComponents();



        jTextField1.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = jTextField1.getText();
                l1[0] = value.length();
                if ( l1[0]<4 && ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9' || ke.getKeyCode() ==8 ) {
                    jTextField1.setEditable(true);


                } else {
                    jTextField1.setEditable(false);

                }
            }
        });


        jTextField2.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = jTextField2.getText();
                  l2[0] = value.length();
                if (  l2[0]<4 && ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9' || ke.getKeyCode() ==8 ) {
                    jTextField2.setEditable(true);


                } else {
                    jTextField2.setEditable(false);

                }
            }
        });


        jTextField3.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = jTextField3.getText();
                  l3[0] = value.length();
                if (  l3[0]<4 && ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9' || ke.getKeyCode() ==8 ) {
                    jTextField3.setEditable(true);


                } else {
                    jTextField3.setEditable(false);

                }
            }
        });


        jTextField4.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = jTextField4.getText();
                  l4[0] = value.length();
                if (  l4[0]<4 && ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9' || ke.getKeyCode() ==8 ) {
                    jTextField4.setEditable(true);


                } else {
                    jTextField4.setEditable(false);

                }
            }
        });


        jPasswordField1.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = jPasswordField1.getText();
                  l5[0] = value.length();
                if (  l5[0]<3 && ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9' || ke.getKeyCode() ==8 ) {
                    jPasswordField1.setEditable(true);


                } else {
                    jPasswordField1.setEditable(false);

                }
            }
        });
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ButPurcTrip = new javax.swing.JButton();
        ButPurcGuncelle = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Card No");

        ButPurcTrip.setText("Purchase");
        ButPurcTrip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButPurcTripMouseClicked(evt);
            }
        });

        ButPurcGuncelle.setText("Purchase");
        ButPurcGuncelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButPurcGuncelleMouseClicked(evt);
            }
        });

        jLabel2.setText("CVC Code");

        jLabel3.setText("Expiration Date");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButPurcTrip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButPurcGuncelle))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButPurcTrip)
                    .addComponent(ButPurcGuncelle))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButPurcTripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButPurcTripMouseClicked
        // TODO add your handling code here:




       if ( l1[0]>=3 && l2[0]>=3 && l3[0]>=3 && l4[0]>=3  && l5[0]>=2  ) {



           PreparedStatement ps1;
           PreparedStatement ps2;


           try {

               String [] bankalar = new String[] {"Ziraat Bankası", "İşBank", "INGBank","Vakıfbank","Denizbank","Garanti Bankası"};
               LocalDateTime tarih = LocalDateTime.now();
               DateTimeFormatter dtf = DateTimeFormatter.ofPattern("YYYY-MM-dd");
               System.out.println(dtf.format(tarih));
               String date2 = dtf.format(tarih);
               int sec = (int) (Math.random() * bankalar.length);


               String query4 = "INSERT INTO `booking`( `Book Date`, `Booking Type` ,`Pay Account`,`Pay Date`) VALUES(?,?,?,?) ";

               ps1 = NewClass.getConnection().prepareStatement(query4);
               ps1.setDate(1, Date.valueOf(date2));
               ps1.setString(2, "Purchased");
               ps1.setString(3, bankalar[sec]);
               ps1.setDate(4, Date.valueOf(date2));

               if (ps1.executeUpdate() > 0) {

              //     JOptionPane.showMessageDialog(null, "New user Add");
               }


               ResultSet rs2;

               String query5 = "SELECT `Booking ID` FROM booking WHERE `Book Date` =? ";

               int bookid=0;
               ps2 = NewClass.getConnection().prepareStatement(query5);
               ps2.setDate(1, Date.valueOf(date2));
               rs2=ps2.executeQuery();

               while (rs2.next()) {

                   if (rs2.isLast()) {

                       bookid = rs2.getInt(1);
                   }
               }



               String query3 = "INSERT INTO `manage`( `Cus ID`, `Book ID` , `Trip ID`) VALUES (?,?,?)";

               ps1 = NewClass.getConnection().prepareStatement(query3);
               ps1.setInt(1, Login.cusid);
               ps1.setInt(2, bookid);
               ps1.setInt(3, Trip.Tripid );

              if (ps1.executeUpdate() > 0) {

                 JOptionPane.showMessageDialog(null, "Succesfully purchased");

                  setVisible(false);
                  Trip.trip.setVisible(false);


              }


           }
           catch (Exception a) {

               System.out.println(a.getMessage());
           }


       }


       else {

           jTextField1.setText("");
           jTextField2.setText("");
           jTextField3.setText("");
           jTextField4.setText("");
           jPasswordField1.setText("");
           JOptionPane.showMessageDialog(null, "Please check the information and try again");

       }




    }//GEN-LAST:event_ButPurcTripMouseClicked

    private void ButPurcGuncelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButPurcGuncelleMouseClicked
        // TODO add your handling code here:



        if ( l1[0]>=3 && l2[0]>=3 && l3[0]>=3 && l4[0]>=3  && l5[0]>=2  ) {


            ResultSet rs3;
            PreparedStatement ps1;

            int bookid = 0;

            String[] bankalar = new String[]{"Ziraat Bankası", "İşBank", "INGBank", "Vakıfbank", "Denizbank", "Garanti Bankası"};
            LocalDateTime tarih = LocalDateTime.now();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("YYYY-MM-dd");
            String date2 = dtf.format(tarih);

            try {

                String query3 = "SELECT `Book ID` FROM `manage` WHERE `Cus ID`=?  And  `Trip ID`=?";
                ps1 = NewClass.getConnection().prepareStatement(query3);
                ps1.setInt(1, Login.cusid);
                ps1.setInt(2, BilgiUpdate.tripid);
                rs3 = ps1.executeQuery();
                if (rs3.next()) {

                    bookid = rs3.getInt(1);
                    int sec = (int) (Math.random() * bankalar.length);

                    String pur = "Purchased";

                    try {
                        String query2 = "UPDATE `booking` SET `Booking Type`=?,`Pay Account`=?,`Pay Date`=? WHERE `Booking ID`=?";

                        ps1 = NewClass.getConnection().prepareStatement(query2);
                        ps1.setString(1, pur);
                        ps1.setString(2, bankalar[sec]);
                        ps1.setDate(3, Date.valueOf(date2));
                        ps1.setInt(4, bookid);
                        if (ps1.executeUpdate() > 0) {

                          JOptionPane.showMessageDialog(null, "Successfully purchased");


                        }


                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                    }
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

            int SelectedRow = Profile.b.getTableRez().getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) Profile.b.getTableRez().getModel();
            model.setValueAt("Purchased", SelectedRow, 1);
            Profile.b.getTableRez().setModel(model);

        }

        else {

            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jPasswordField1.setText("");

            JOptionPane.showMessageDialog(null, "Please check the information and try again");
            setVisible(false);
        }


    }//GEN-LAST:event_ButPurcGuncelleMouseClicked



    /**
     * @param args the command line arguments
     */


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               purcc.setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButPurcGuncelle;
    private javax.swing.JButton ButPurcTrip;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
